version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: job-fair-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: job_fair
      MYSQL_USER: jobuser
      MYSQL_PASSWORD: jobpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    platform: linux/arm64/v8

volumes:
  mysql_data: